In [1]:
from sklearn.svm import SVC
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [2]:
df=datasets.load_iris(as_frame=True).frame

In [3]:
df.head() # multiclass classification

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  target
0                5.1               3.5                1.4               0.2       0
1                4.9               3.0                1.4               0.2       0
2                4.7               3.2                1.3               0.2       0
3                4.6               3.1                1.5               0.2       0
4                5.0               3.6                1.4               0.2       0

In [8]:
df.isnull().sum()
df.shape

(150, 5)

In [6]:
df['target'].value_counts()

target
0    50
1    50
2    50
Name: count, dtype: int64

In [10]:
x=df.drop('target',axis=1)
y=df['target']

In [11]:
x.head()

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [12]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: target, dtype: int64

In [13]:
x_train,x_test,y_train,y_test=train_test_split(
    x,y,test_size=0.3,random_state=42,stratify=y ## imbalance dataset er jonno
)

In [14]:
x_train.shape

(105, 4)

In [15]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [21]:
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [22]:
#model
svc=SVC()

svc.fit(x_train_scaled,y_train)

SVC()

In [23]:
y_pred=svc.predict(x_test_scaled)

In [27]:
## Evaluate
from sklearn.metrics import accuracy_score,classification_report,f1_score
print("accuracy: ",accuracy_score(y_test,y_pred))
print("classification report: \n",classification_report(y_test,y_pred))
print("f1 score:", f1_score(y_test, y_pred, average='weighted'))

accuracy:  0.9333333333333333
classification report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.88      0.93      0.90        15
           2       0.93      0.87      0.90        15

    accuracy                           0.93        45
   macro avg       0.93      0.93      0.93        45
weighted avg       0.93      0.93      0.93        45

f1 score: 0.9332591768631814

In [29]:
# linear kernel
svc=SVC(kernel='linear')

svc.fit(x_train_scaled,y_train)

y_pred=svc.predict(x_test_scaled)

print("accuracy: ",accuracy_score(y_test,y_pred))

accuracy:  0.9111111111111111

In [31]:
# polynomial kernel
svc=SVC(kernel='poly')

svc.fit(x_train_scaled,y_train)

y_pred=svc.predict(x_test_scaled)

print("accuracy: ",accuracy_score(y_test,y_pred))

accuracy:  0.8666666666666667

In [32]:
# sigmoid kernel
svc=SVC(kernel='sigmoid')

svc.fit(x_train_scaled,y_train)

y_pred=svc.predict(x_test_scaled)

print("accuracy: ",accuracy_score(y_test,y_pred))

accuracy:  0.9111111111111111

In [34]:
C_vals=[0.5,1,2,3,4,5]

for c_val in C_vals:
    svc=SVC(c_val,kernel='rbf')

    svc.fit(x_train_scaled,y_train)

    y_pred=svc.predict(x_test_scaled)

    print("C= ",c_val, "& accuracy: ",accuracy_score(y_test,y_pred))

TypeError: SVC.__init__() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given